export const status = {
  NEW_GAME: "NEW_GAME",
  WAITING_FOR_OPPONENT: "WAITING_FOR_OPPONENT",
  ACTIVE_GAMES: "ACTIVE_GAMES",
  ERROR: "ERROR",
  YOUR_ROUND: "YOUR_ROUND",
  JOIN: "JOIN",
  ROUND: "ROUND",
  WINNER: "WINNER",
  GAME_OVER: "GAME_OVER",
  DISCONNECT: "DISCONNECT",
  CURRENT_GAME: "CURRENT_GAME",
  RESTART: "RESTART",
};
